---
- name: Install python-augeas on remote node
  package:
    name: python-augeas
    state: present

- name: set facts
  set_fact:
    tmp_service: "{{ service }}"
    tmp_state: "{{ state }}"
    tmp_host_list: "{{ host_list }}"

- name: add service conf
  include_tasks: add-service.yml
  when: tmp_state == "present"

- name: add service conf
  include_tasks: remove-service.yml
  when: tmp_state == "absent"
